[package]
name = "btrfs-dedupe"
version = "1.0.1"
description = "BTRFS whole-file deduplication tool"
license = "MIT"
homepage = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup/tree/master/btrfs-dedupe"
repository = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup/tree/master/btrfs-dedupe"

authors = [
	"James Pharaoh <james@pharaoh.uk>",
]

include = [
	"Cargo.toml",
	"README.md",
	"src/**/*",
]

[dependencies]
btrfs = "1.0"
clap = "2.18"
sha2 = "0.2"
termion = "1.1"
