[package]
name = "btrfs-dedupe"
version = "1.0.1"
description = "BTRFS whole-file deduplication tool"
license = "Apache-2.0"

authors = [
	"James Pharaoh <james@pharaoh.uk>",
]

include = [
	"Cargo.toml",
	"README.md",
	"src/**/*",
]

[dependencies]
btrfs = "1.0"
clap = "2.18"
sha2 = "0.2"
termion = "1.1"
